### ISSUE TITLE
Installing contributed apps

### ISSUE THREAD

**Issue by ocet** [tyll/tinyos-2.x-contrib#1]
I have no troubles with running apps from 2.1.2 release of TinyOS, but I can't figure out how to build any of contributed apps. Do I just copy directory structure from app directory to TOSROOT? During make install I get various errors saying I miss some dependancies. 

During installation of tinyos-2.x-contrib/ethz/snpk/apps/MultihopOscilloscope ( I copied apps directory t my $TOSROOT and merged it with $TOSROOT/apps).
http://pastebin.com/6KAJ5qF1

**Comment by tyll** [comment]
Sorry, this here is just an old mirror of the CVS contents. Please ask for support via the current upstream: http://tinyos.net/ - I do not use tinyos anymore and cannot help you.
